$('.owl-carousel').owlCarousel({ 
  autoplay:true,
  responsive:{
              0:{
                  items:1
              },
              1100:{
                  items:5
              }
          }
      });